// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package top.alvinsite.chat.common.packets;

public interface ChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .MessageType type = 1;</code>
   */
  boolean hasType();
  /**
   * <code>required .MessageType type = 1;</code>
   */
  top.alvinsite.chat.common.packets.MessageType getType();

  /**
   * <code>required .ReceiverType receiverType = 2;</code>
   */
  boolean hasReceiverType();
  /**
   * <code>required .ReceiverType receiverType = 2;</code>
   */
  top.alvinsite.chat.common.packets.ReceiverType getReceiverType();

  /**
   * <code>optional string receiver = 5;</code>
   */
  boolean hasReceiver();
  /**
   * <code>optional string receiver = 5;</code>
   */
  java.lang.String getReceiver();
  /**
   * <code>optional string receiver = 5;</code>
   */
  com.google.protobuf.ByteString
      getReceiverBytes();

  /**
   * <code>optional string content = 6;</code>
   */
  boolean hasContent();
  /**
   * <code>optional string content = 6;</code>
   */
  java.lang.String getContent();
  /**
   * <code>optional string content = 6;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
