// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package top.alvinsite.chat.common.packets;

public interface ChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 type = 1;</code>
   */
  boolean hasType();
  /**
   * <code>required int32 type = 1;</code>
   */
  int getType();
}
