// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package top.alvinsite.chat.common.packets;

/**
 * Protobuf enum {@code ReceiverType}
 */
public enum ReceiverType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SYSTEM = 1;</code>
   */
  SYSTEM(1),
  /**
   * <code>USER = 2;</code>
   */
  USER(2),
  /**
   * <code>GROUP = 3;</code>
   */
  GROUP(3),
  ;

  /**
   * <code>SYSTEM = 1;</code>
   */
  public static final int SYSTEM_VALUE = 1;
  /**
   * <code>USER = 2;</code>
   */
  public static final int USER_VALUE = 2;
  /**
   * <code>GROUP = 3;</code>
   */
  public static final int GROUP_VALUE = 3;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ReceiverType valueOf(int value) {
    return forNumber(value);
  }

  public static ReceiverType forNumber(int value) {
    switch (value) {
      case 1: return SYSTEM;
      case 2: return USER;
      case 3: return GROUP;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ReceiverType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ReceiverType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ReceiverType>() {
          public ReceiverType findValueByNumber(int number) {
            return ReceiverType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return top.alvinsite.chat.common.packets.Chat.getDescriptor()
        .getEnumTypes().get(1);
  }

  private static final ReceiverType[] VALUES = values();

  public static ReceiverType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ReceiverType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ReceiverType)
}

